# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Names for the per-step vLLM engine metrics: vLLM's, and the ones we log.

Split out of ``utils.py`` (which imports torch) so the declarations stay
importable on their own, and kept beside ``compute_engine_step_metrics``, which
is what produces the keys.
"""

from __future__ import annotations

from nemo_rl.telemetry.vocabulary import (
    RecordedMetric,
    TeedMetric,
    register_recorded_metrics,
    register_teed_metrics,
)

# Engine series surfaced per step, beyond the spec-decode family. These are the
# family names vLLM registers (vllm/v1/metrics/loggers.py); its reader returns
# family names, which prometheus_client strips of ``_total``, so no suffixed
# alias is needed here (unlike the HTTP-scrape path in dynamo/metrics.py).
# test_engine_metric_names_match_vllm checks these against vLLM itself.
PROMPT_TOKEN_COUNTERS = ("vllm:prompt_tokens",)
GENERATION_TOKEN_COUNTERS = ("vllm:generation_tokens",)
PROMPT_LENGTH_HISTOGRAMS = ("vllm:request_prompt_tokens",)
GENERATION_LENGTH_HISTOGRAMS = ("vllm:request_generation_tokens",)
REQUEST_SUCCESS_COUNTERS = ("vllm:request_success",)

# vLLM's FinishReason vocabulary: stop, length, abort, error, repetition. Only
# the first two leave a usable sample behind -- ``length`` is a normal outcome in
# RL, where a rollout routinely runs to max_tokens. Everything else is counted as
# failed rather than dropped, so ok + failed stays equal to the engine's total
# even if a future vLLM adds a reason we have never heard of.
OK_FINISH_REASONS = frozenset({"stop", "length"})
FINISHED_REASON_LABEL = "finished_reason"

# Keys compute_engine_step_metrics writes.
PROMPT_TOKENS_KEY = "vllm/prompt_tokens"
GENERATION_TOKENS_KEY = "vllm/generation_tokens"
PROMPT_LENGTH_MEAN_KEY = "vllm/prompt_length_mean"
GENERATION_LENGTH_MEAN_KEY = "vllm/generation_length_mean"
GENERATIONS_OK_KEY = "vllm/generations_ok"
GENERATIONS_FAILED_KEY = "vllm/generations_failed"

# Distinct from the driver-side ``gen_ai.*`` series, which are derived from the
# tensors a generate() call returns: these are the engine's own accounting, and
# the sequence-length and abort counts cannot be reconstructed driver-side at
# all. Counters carry the per-step delta, so adding deltas reconstructs the run
# total.
VLLM_TEED_METRICS = (
    TeedMetric(
        PROMPT_TOKENS_KEY,
        "rl.vllm.prompt_tokens",
        kind="counter",
        unit="{token}",
        description="Prompt tokens processed by the vLLM engine.",
    ),
    TeedMetric(
        GENERATION_TOKENS_KEY,
        "rl.vllm.generation_tokens",
        kind="counter",
        unit="{token}",
        description="Tokens generated by the vLLM engine.",
    ),
    TeedMetric(
        PROMPT_LENGTH_MEAN_KEY,
        "rl.vllm.prompt_length.mean",
        unit="{token}",
        description="Mean prompt sequence length over the step.",
    ),
    TeedMetric(
        GENERATION_LENGTH_MEAN_KEY,
        "rl.vllm.generation_length.mean",
        unit="{token}",
        description="Mean generated sequence length over the step.",
    ),
    TeedMetric(
        GENERATIONS_OK_KEY,
        "rl.vllm.generations.ok",
        kind="counter",
        unit="{generation}",
        description="Generations the engine finished normally.",
    ),
    TeedMetric(
        GENERATIONS_FAILED_KEY,
        "rl.vllm.generations.failed",
        kind="counter",
        unit="{generation}",
        description="Generations the engine aborted rather than finished.",
    ),
)

register_teed_metrics(VLLM_TEED_METRICS)


#: Wall clock of one batched ``generate()`` call, driver side.
BATCH_DURATION_METRIC = "rl.vllm.batch.duration"

# Its own series rather than gen_ai.server.request.duration: that histogram is
# defined per inference request, and one call here covers a whole batch across
# every data-parallel shard, so its samples would not be comparable with any
# other producer's. The gen_ai token counts are per-batch sums, which stay
# additive, so those still go to the semconv instruments.
VLLM_RECORDED_METRICS = (
    RecordedMetric(
        BATCH_DURATION_METRIC,
        kind="histogram",
        unit="s",
        description="Wall clock of one batched generate() call, driver side.",
    ),
)

register_recorded_metrics(VLLM_RECORDED_METRICS)

#: Registry key the series above is recorded against.
BATCH_DURATION_KEY = VLLM_RECORDED_METRICS[0].key
